### ISSUE TITLE
Ingest new MONDO releases to GCS

### ISSUE THREAD

**Issue by larrybabb** [clingen-data-model/data-exchange-topics#15]
This is the first task in the process of publishing the MONDO release's Actual Disease Renames and Planned Disease Record Obsoletions. 

MONDO's releases are published at https://github.com/monarch-initiative/mondo/releases

The proposed solution is to poll the Git API to the monarch-initative/mondo releases to determine when a new release is posted. Maybe if the release is the same day as the polling request that will be sufficient, otherwise we may need to keep a record of the last release that was collected so that if the polling service fails we can be sure to pick up any releases that were missed.

Once we have a polling service that recognizes a new release is available, we will want to capture 2 artifacts. One is the actual Text associated with the release, as it contains headers with details of the changes in the release. One section is titled Renamed Diseases. This section's header and content should be extracted to a file. Additionally, we will want to capture a specifically named TSV file in the released files called <TBD> which will contain the planned records that will be obsoleted from MONDO in the near future.

These two files Actual Disease Renames and Planned Disease Obsoletions will be used in the next step and processed into individual JSON records and posted to the ClinGen Data Exchange Topic for consumption by various ClinGen applications/systems.

**Comment by KelseaChang5** [comment]
@sjahl Could you please clarify what this issue is about? Larry is confused about the reference to GSC. If this is no longer needed please let us know and we'll archive it. Thanks!

**Comment by sjahl** [comment]
@KelseaChang5 I think the original MVP that @larrybabb  described to me had us downloading the TSV files from Mondo and storing them in a google cloud storage bucket. Since then, I think we've gone in another direction where Larry is writing a function to get the data and send it off to our kafka cluster directly without the interim bucket.

So we can probably close this (the cloudfunction -> kafka plumbing is all set).
