### ISSUE TITLE
Clean up Data Exchange Inventory Sheet

### ISSUE THREAD

**Issue by KelseaChang5** [clingen-data-model/data-exchange-topics#20]
**To Do**
- Have slotted topics deleted (contact Kyle for this) _Completed_
- Add titles for each topic _Completed_
- Reach out to those with incomplete descriptions/if more information is needed _Completed_
- Ask Steven about which ones are backed up to Google Cloud (then add column in sheet with this information) _Completed_

**Link to Sheet:**
[https://docs.google.com/spreadsheets/d/1yuO9-IM-2MRM1AacKekNJdHRb8fl6ozxO7OFu6WPQ2Q/edit#gid=0](url)

**Comment by larrybabb** [comment]
@KelseaChang5 - two things here... 

1. reminder to incorporate this work into an SOP (additional tickets) to keep it current, sustainable and accessible to others.

1. FYI - [here's a related google doc ](https://docs.google.com/document/d/19D9QmxxzlxQEvMzNNpKccCx_e3Sj8bXZcEEIWN7zK5A/edit#heading=h.fenoub4nlwwx) that Kyle has been working on that should somehow be integrated into the documentation that is available to the developers that would be interested in the list of topcis.

**Comment by KelseaChang5** [comment]
> @KelseaChang5 - two things here...
> 
> 1. reminder to incorporate this work into an SOP (additional tickets) to keep it current, sustainable and accessible to others.
> 2. FYI - [here's a related google doc ](https://docs.google.com/document/d/19D9QmxxzlxQEvMzNNpKccCx_e3Sj8bXZcEEIWN7zK5A/edit#heading=h.fenoub4nlwwx) that Kyle has been working on that should somehow be integrated into the documentation that is available to the developers that would be interested in the list of topcis.

- Added to Project Management Epic
- Added the Dev Guide to the [ClinGen Data Exchange Google Site](https://sites.google.com/broadinstitute.org/clinical-genome-resource/data-platform-working-group/data-exchange-directory)
