### ISSUE TITLE
[New Topic]: allele registry topic

### ISSUE THREAD

**Issue by kriehle** [clingen-data-model/data-exchange-topics#22]
### Topic Producer/Developer Contact Details

riehle@bcm.edu

### Topic Consumer/User Information

Users / tools interested in the Allele Registry

### Topic Name (suggested)

car

### Topic Description

Message queue to hold information sourced from the ClinGen Allele Registry.  Potential examples include pushing messages reflecting newly registered CA, CACN, etc. IDs. 

### Number of partitions

1 (recommended)

### Message Persistence

Indefinitely (yes)

### Can the data in this topic be shared publicly?

Yes.  If we need a non-public topic we will utilize a new topic. 

### Which clusters should this topic be created on?

- [X] staging
- [X] production

### Do you want to have the topic backed up to GCS?

- [ ] backup to GCS

**Comment by theferrit32** [comment]
@kriehle, the topic `allele-registry` has been added and ACLs updated for the BaylorStaging and BaylorProduction service accounts. I've also given the BaylorStaging service account the ability to delete and re-create the staging topic, if you need to at some point reset the contents and offsets of messages on it.

### staging:
topic: `allele-registry`
service account: BaylorStaging (ACLs: read, write, delete, create)

### production:
topic: `allele-registry`
service account: BaylorProduction (ACLs: read, write)
