### ISSUE TITLE
VCV Dev Guide

### ISSUE THREAD

**Issue by KelseaChang5** [clingen-data-model/data-exchange-topics#24]
Draft dev guide for Baylor team for initial VCV message stream

**Comment by theferrit32** [comment]
Added document here:
https://docs.google.com/document/d/1Cd1R5EvWK4cpzsaK2ZYCli75Pqz93__xPfkIFn_hXi8/edit#heading=h.ixqukpnn9hcb

**Comment by larrybabb** [comment]
what's the deal @larrybabb ?

**Comment by larrybabb** [comment]
I say we call this beta, since the VCV work is on hold for now. We will create a new ticket for finalizing this once we have a clear picture of what we consider done for the VCV work.
