### ISSUE TITLE
Automated Updates of Data Exchange Topic Inventory

### ISSUE THREAD

**Issue by KelseaChang5** [clingen-data-model/data-exchange-topics#25]
**Goal:** Establish a process to keep this document up-to-date with new topics that have been created since last check in. 

Data Exchange Topic Inventory: https://docs.google.com/spreadsheets/d/1yuO9-IM-2MRM1AacKekNJdHRb8fl6ozxO7OFu6WPQ2Q/edit#gid=0

**Comment by KelseaChang5** [comment]
@theferrit32 Would you have any input on to the best way to go about keeping this topic inventory sheet updated/the best way to pull topics created within a certain time frame?

**Comment by theferrit32** [comment]
I recommend archiving this ticket until we decide this is worth doing.

There's a script here which could be used and enhanced to automate generating a spreadsheet with some of the info we want.

https://github.com/clingen-data-model/data-exchange-topics/blob/276898e1373881d5f22357026476bbeee8d30a85/src/topic_utils/topic_metrics.clj

Some of the information in the current inventory sheet is not automatable, like owner and descriptions we filled in manually. We could have that sheet pull information from another sheet/page in the same document that has information like most recent message time and number of messages.

Google Sheets Java API
https://developers.google.com/sheets/api/quickstart/java
https://github.com/googleworkspace/java-samples/blob/master/sheets/snippets/src/main/java/SpreadsheetSnippets.java

**Comment by larrybabb** [comment]
closing this for now. we can reopen in the future. it was not done.
