### ISSUE TITLE
Give baylor groups read and write access to the topic "gpm-general-events" for all the available instances

### ISSUE THREAD

**Issue by neethushah** [clingen-data-model/data-exchange-topics#27]
### Topic Producer/Developer Contact Details

neethu.shah@bcm.edu

### Topic Consumer/User Information

CSpec Registry

### Topic Name (suggested)

gpm-general-events

### Topic Description

Please give all Baylor consumer groups(baylor_dev, baylor_staging, baylor_production) read and write access to the topic _gpm-general-events_ 

### Number of partitions

1 (recommended)

### Message Persistence

Indefinitely (yes)

### Which clusters should this topic be created on?

- [X] staging
- [X] production

### Do you want to have the topic backed up to GCS?

- [ ] backup to GCS

**Comment by theferrit32** [comment]
@neethushah baylor dev/stage/prod service accounts have been given read access to `gpm-general-events` on their respective dev/stage/prod clusters.
