### ISSUE TITLE
Requesting read access to mondo-notifications

### ISSUE THREAD

**Issue by nshahvr** [clingen-data-model/data-exchange-topics#30]
### Topic Producer/Developer Contact Details

neethu.shah@bcm.edu

### Topic Consumer/User Information

Actionability

### Topic Name (suggested)

mondo-notifications

### Topic Description

Please give read access to mondo-notifications topic

### Number of partitions

1 (recommended)

### Message Persistence

Indefinitely (yes)

### Which clusters should this topic be created on?

- [X] staging
- [X] production

### Do you want to have the topic backed up to GCS?

- [ ] backup to GCS

**Comment by nshahvr** [comment]
Please give all Baylor consumer groups(baylor_dev, baylor_staging, baylor_production) read access to the topic mondo-notifications

**Comment by theferrit32** [comment]
I've granted baylor_dev, baylor_staging, baylor_production read access to `mondo-notifications` on each cluster, but it only currently exists on the production cluster so the other two will not receive any messages (or will get a topic-does-not-exist exception, depending on the kafka client) if they try to read from it.
