### ISSUE TITLE
UNC groups need consume access to mondo-notifications topic

### ISSUE THREAD

**Issue by yugen** [clingen-data-model/data-exchange-topics#31]
In order to complete high priority items in the current SP cycle the UNC groups (`unc_development`, `unc_staging`, and `unc_production`) request consumer access to the `mondo-notifications` topic.

Thanks for your help!

**Comment by theferrit32** [comment]
I've granted the keys for `unc_development`, `unc_staging`, and `unc_production` access to the `mondo-notifications` topic on their respective kafka clusters, but at the moment that topic only exists on the production cluster. If you need a deployment running in separate contexts at the same time to read from the production `mondo-notifications` topic without interfering with each other, you can use additional consumer groups built off the `unc_production` group prefix, such as `unc_production_dev` and `unc_production_staging`.
