### ISSUE TITLE
[New Topic]: cspec-general

### ISSUE THREAD

**Issue by neethushah** [clingen-data-model/data-exchange-topics#32]
### Topic Producer/Developer Contact Details

neethu.shah@bcm.edu

### Topic Consumer/User Information

GPM, Website

### Topic Name (suggested)

cspec-general

### Topic Description

Please add the topic _cspec-general_ to staging and production instances and five read AND WRITE permissions to baylor consumer groups - baylor_staging and baylor_production respectively.

### Number of partitions

1 (recommended)

### Message Persistence

Indefinitely (yes)

### Which clusters should this topic be created on?

- [X] staging
- [X] production

### Do you want to have the topic backed up to GCS?

- [ ] backup to GCS

**Comment by theferrit32** [comment]
@neethushah the topic `cspec-general` has been created on the staging and production clusters, and read/write access granted to the key for consumer groups `baylor_staging` and `baylor_production` respectively.
