### ISSUE TITLE
[New Topic]: dosage-sensitivity-events for the new DCI2 to start using

### ISSUE THREAD

**Issue by plweller3** [clingen-data-model/data-exchange-topics#34]
### Topic Producer/Developer Contact Details

pweller1@geisinger.edu

### Topic Consumer/User Information

DCI2, website, genegraph, 

### Topic Name (suggested)

dosage-sensitivity-events

### Topic Description

This topic queue will be used to as part of the new DCI 2 project for broadcasting curation events.

### Number of partitions

1 (recommended)

### Message Persistence

Indefinitely (yes)

### Can the data in this topic be shared publicly?

Restricted access is fine.  We could create a separate one for public access if the need ever arises, but that is not the purpose of this one.

### Which clusters should this topic be created on?

- [X] staging
- [X] production

### Do you want to have the topic backed up to GCS?

- [X] backup to GCS

**Comment by larrybabb** [comment]
@plweller3 I set the topic *dosage-sensitivity-events* up on dev, stage and prod as requested. I provided read/write access to the web-dev, web-stage and web-prod API key accounts as well.

If there are any additional concerns or issues with this please reopen or add a new ticket.

**Comment by larrybabb** [comment]
@theferrit32 Can you explain to me how we set up the topic to be automatically backed up?

**Comment by theferrit32** [comment]
@larrybabb we currently only back up things on the prod cluster. The topics have to be explicitly added to the backup sink in Confluent.

Confluent -> prod cluster -> data integration -> connectors -> clingen_topic_gcs_backups -> settings -> topics

**Comment by larrybabb** [comment]
Thx.
