### ISSUE TITLE
[New Topic]: mondo-notifications

### ISSUE THREAD

**Issue by neethushah** [clingen-data-model/data-exchange-topics#38]
### Topic Producer/Developer Contact Details

neethu.shah@bcm.edu

### Producer API Key

no write access requested

### Topic Consumer/User Information

baylor_staging, baylor_dev

### Topic Name (suggested)

mondo-notifications

### Topic Description

Requesting read access to the stage instance of mono-notifications for both baylor_dev and baylor_staging consumer groups

### Number of partitions

1 (recommended)

### Message Persistence

Indefinitely (yes)

### Which clusters should this topic be created on?

- [X] staging
- [ ] production

### Do you want to have the topic backed up to GCS?

- [ ] backup to GCS

**Comment by theferrit32** [comment]
I've created a `mondo-notifications` topic on the stage and dev clusters and copied the contents of the prod `mondo-notifications` topic to those, and given `baylor_stage` and baylor_dev` groups access to their respective one. Each has the same 4886 messages as of today, and just won't receive any further updates that go to the prod topic.
