### ISSUE TITLE
[New Topic]: gpm-person-events

### ISSUE THREAD

**Issue by yugen** [clingen-data-model/data-exchange-topics#39]
### Topic Producer/Developer Contact Details

jward3@email.unc.edu

### Producer API Key

staging: JQW2WQAOG2IYVPXF; production: 7VYSLPCEADGJOOES

### Topic Consumer/User Information

GeneTracker, CCDB, Website, CSPEC, GCI/VCI (?)

### Topic Name (suggested)

gpm-person-events

### Topic Description

The `gpm-person-events` topic publishes event messages about people in the GPM.
Messages in this topic will only include be about people in the GPM. For messages about group status, scope, and membership please see the `gpm-general-events` topic.

This topic is intended for use by other ClinGen applications that would like to monitor person information and/or keep their own records synchronized with the GPM. The primary use case is to share data about ClinGen membership with [clinicalgenome.org](https://clinicalgenome.org/).

For more information read the [documentation](https://github.com/clingen-data-model/gpm/blob/master/public/data-exchange/gpm-person-events.md)

### Number of partitions

1 (recommended)

### Message Persistence

Indefinitely (yes)

### Can the data in this topic be shared publicly?

This topic should be be available publicly.  Some data will be eventually be published to the https://clinicalgenome.org

### Which clusters should this topic be created on?

- [X] staging
- [X] production

### Do you want to have the topic backed up to GCS?

- [X] backup to GCS

**Comment by yugen** [comment]
@theferrit32 Giving this a bump so it doesn't fall off the radar.

**Comment by theferrit32** [comment]
@yugen Done! I don't know when the clinicalgenome.org website intends to show these updates but I've granted that team read access to the stage and prod topic.

**Comment by yugen** [comment]
Thanks @theferrit32!
