### ISSUE TITLE
Please Create / Add to Kafka Topics

### ISSUE THREAD

**Issue by plweller3** [clingen-data-model/data-exchange-topics#4]
Team,

Please create web-dev, web-stage, and web-prod accounts for website to access/use various kafka topic streams.

Please give all three accounts the ability to access (read only) the following existing streams:

      gt-precuration-events
      gene_validity_raw
      gene_validity_events

Also, please create two new topic streams and give three new accounts full read/write access:

        gpm-general-events
        web-group-events

A brief description of the two new streams is as follows:
    
    gpm-general-events:  The production topic stream that the EPAM/GPM will be broadcasting updates to.
    web-group-events:  The production topic stream that the website will be broadcasting EP updates to.

Also, in the the past, to get a list of all topics one could just access a github file or log onto the old AWS server.  Since that has all moved into the cloud, I'm not sure where the list of all topics reside.  Can you provide the list, or better yet, point me to where to get it so we can keep up to date, including letting you know if any old ones can be released.

Thanks!!

CC:  @sgoehringer @yugen

Phil

**Comment by theferrit32** [comment]
@plweller3 The topics `gt-precuration-events`, `gene_validity_raw`, `gene_validity_events`, `gene_dosage` only exist on the stage and prod clusters, and `web-stage` and `web-prod` have been granted read access to those.

`gpm-general-events` and `web-group-events` have been created on all 3 clusters and corresponding `web-*` service accounts granted read/write access.
