### ISSUE TITLE
clinvar-scv-test: GA4GH standard ClinVar SCV sample set for trial and testing

### ISSUE THREAD

**Issue by larrybabb** [clingen-data-model/data-exchange-topics#40]
### Topic Producer/Developer Contact Details

lbabb@broadinstitute.org

### Producer API Key

B/G APi key for stage cluster

### Topic Consumer/User Information

LDH needs this in staging cluster to begin dev and testing

### Topic Name (suggested)

clinvar-scv-test

### Topic Description

Dev topic loaded with clinvar variations followed by SCVs for GK-Pilot dataset released at 10th GA4GH plenary. This is a subset of SCVs and variations from the 9/3/2022 clinvar release. See https://github.com/ga4gh/gk-pilot/tree/main/datasets/clinvar for the source of records planned for this topic.

### Number of partitions

1 (recommended)

### Message Persistence

Indefinitely (yes)

### Can the data in this topic be shared publicly?

sure, but not necessary

### Which clusters should this topic be created on?

- [X] staging
- [ ] production

### Do you want to have the topic backed up to GCS?

- [ ] backup to GCS

**Comment by larrybabb** [comment]
@theferrit32 please put this on the staging cluster since it's a topic that may be used by multiple groups for testing.

**Comment by theferrit32** [comment]
@larrybabb done. `clinvar-scv-test` is on stage with the VariationDescriptors followed by the 3 types of Statements. Baylor staging service account has been given access.
