### ISSUE TITLE
Read access to variant_interpretation_dev on the production instance

### ISSUE THREAD

**Issue by neethushah** [clingen-data-model/data-exchange-topics#47]
### Topic Producer/Developer Contact Details

neethu.shah@bcm.edu

### Producer API Key

3G6DVESEOY45PCJB

### Topic Consumer/User Information

ERepo

### Topic Name (suggested)

variant_interpretation_dev

### Topic Description

variant_interpretation_dev topic exists on the production kafka instance and the baylor production consumer group requires read access to it. So, requesting for read access.

### Number of partitions

1 (recommended)

### Message Persistence

Indefinitely (yes)

### Which clusters should this topic be created on?

- [ ] staging
- [X] production

### Do you want to have the topic backed up to GCS?

- [ ] backup to GCS

**Comment by kriehle** [comment]
I added READ access to variant_interpretation_dev on production for the baylor consumer group.

**Comment by theferrit32** [comment]
Thanks @kriehle !
