### ISSUE TITLE
New topic request on dev, stage, and prod: vci2erepo-ack 

### ISSUE THREAD

**Issue by kriehle** [clingen-data-model/data-exchange-topics#48]
### Topic Producer/Developer Contact Details

riehle@bcm.edu

### Producer API Key

BaylorDev

### Topic Consumer/User Information

VCI

### Topic Name (suggested)

vci2erepo-ack

### Topic Description

To fulfill the requirement of acknowledging a successful publication in the ERepo for consumption and display within the VCI.
We would like to have dev, stage, and prod topics of this name.

### Number of partitions

1 (recommended)

### Message Persistence

Indefinitely (yes)

### Can the data in this topic be shared publicly?

Sure. I believe that only the VCI would find this information useful, but it's not sensitive. 

### Which clusters should this topic be created on?

- [X] staging
- [X] production

### Do you want to have the topic backed up to GCS?

- [ ] backup to GCS

**Comment by theferrit32** [comment]
@kriehle I added `vci2erepo-ack` to dev, staging, production clusters. Granted `read`, `write`, `create`, `delete` permission to baylor dev/staging/production service account.
