### ISSUE TITLE
[New Topic]: Request for new topic named all-curation-events

### ISSUE THREAD

**Issue by plweller3** [clingen-data-model/data-exchange-topics#49]
### Topic Producer/Developer Contact Details

pweller1@geisinger.edu

### Producer API Key

Eventually there will be multiplem, but for intial dev and test use web-prod and web-stage

### Topic Consumer/User Information

For all activities to send specific events to

### Topic Name (suggested)

all-curation-events

### Topic Description

This topic will be used by all activities to send a specific set of events to.  The initial use case will be to have a single source of all curation history data.  Not the actual details of a curation, but things like version number, change/reason codes and text, date published, etc.  There will almost certainly be other use cases where polling multiple apps for the data is impractical. 
 This request originates from a suggestion Aleks made at a versioning call a few weeks back.  The message structure will be proposed and finalized in the coming months.

### Number of partitions

1 (recommended)

### Message Persistence

Indefinitely (yes)

### Can the data in this topic be shared publicly?

Write permissions should be limited to a curation interface tool (e.g. ACI, VCI, GCI, DCI).  Or the proxy for such tools.  We'll have to work this out with each activity.   It doesn't need to be done now.

### Which clusters should this topic be created on?

- [X] staging
- [X] production

### Do you want to have the topic backed up to GCS?

- [X] backup to GCS

**Comment by plweller3** [comment]
Just wondering what the status of this is.  It says 3 of 3 tasks done.  Does that mean I can use it?

**Comment by theferrit32** [comment]
@plweller3 `all-curation-events` has now been created on stage and prod clusters, with read/write permissions granted to `web-stage` and `web-prod` service accounts
