### ISSUE TITLE
Create topic on staging and production for CSPEC-RULESET

### ISSUE THREAD

**Issue by nshahvr** [clingen-data-model/data-exchange-topics#5]
### Topic Producer/Developer Contact Details

neethu.shah@bcm.edu

### Producer API Key

MUJCMKWG3URDWRB

### Topic Consumer/User Information

Stanford

### What would you like to name your topic?

CSPEC-RULESET

### Number of partitions

1 (recommended)

### Message Persistence

Indefinitely (yes)

### Can the data in this topic be shared publicly?

- The consumer group baylor_staging requires read and write access on the staging instance
- The consumer group baylor_production requires read and write access on the production instance

### Which clusters should this topic be created on?

- [X] staging
- [X] production

**Comment by theferrit32** [comment]
## staging:
- `cspec-ruleset` created on staging cluster. 
  - read/write granted to baylor_staging.
  - read granted to stanford_staging.

## production
- `cspec-ruleset` created on production cluster.
  - read/write granted to baylor_production.
  - read granted to stanford_production.
