### ISSUE TITLE
Write access to variant_interpretation_dev &  variant_interpretation on the production instance

### ISSUE THREAD

**Issue by neethushah** [clingen-data-model/data-exchange-topics#50]
### Topic Producer/Developer Contact Details

neethu.shah@bcm.edu

### Producer API Key

3G6DVESEOY45PCJB

### Topic Consumer/User Information

baylor_production

### Topic Name (suggested)

variant_interpretation  variant_interpretation_dev

### Topic Description

Requesting write access for Baylor

### Number of partitions

1 (recommended)

### Message Persistence

Indefinitely (yes)

### Which clusters should this topic be created on?

- [ ] staging
- [X] production

### Do you want to have the topic backed up to GCS?

- [ ] backup to GCS

**Comment by theferrit32** [comment]
@neethushah done
