### ISSUE TITLE
Request write access to all-curation-events

### ISSUE THREAD

**Issue by neethushah** [clingen-data-model/data-exchange-topics#51]
### Topic Producer/Developer Contact Details

neethu.shah@bcm.edu

### Producer API Key

3G6DVESEOY45PCJB

### Topic Consumer/User Information

baylor_production, baylor_dev, baylor_staging

### Topic Name (suggested)

all-curation-events

### Topic Description

Requesting **read** and **write** access for all the three instances of the Kafka topic **all-curation-events**

### Number of partitions

1 (recommended)

### Message Persistence

Indefinitely (yes)

### Which clusters should this topic be created on?

- [X] staging
- [X] production

### Do you want to have the topic backed up to GCS?

- [ ] backup to GCS

**Comment by theferrit32** [comment]
baylor_staging and baylor_production have now been granted read/write access to the `all-curation-events` topic on the `staging` and `production` clusters, respectively. There is no `all-curation-events` topic on the `dev` cluster right now.
