### ISSUE TITLE
[New Topic]: all-curation-events

### ISSUE THREAD

**Issue by nshahvr** [clingen-data-model/data-exchange-topics#52]
### Topic Producer/Developer Contact Details

neethu.shah@bcm.edu

### Topic Consumer/User Information

baylor_dev

### Topic Name (suggested)

all-curation-events

### Topic Description

Please create all-curation-events kafka topic on dev and give the baylor_dev consumer group read and write permissions. Note that this topic already exists for the stage and prod instance.

### Number of partitions

1 (recommended)

### Message Persistence

Indefinitely (yes)

### Which clusters should this topic be created on?

- [ ] staging
- [ ] production

### Do you want to have the topic backed up to GCS?

- [ ] backup to GCS

**Comment by theferrit32** [comment]
Done. `all-curation-events` created on the `dev` cluster and `read/write` granted to baylor_dev
